package ru.netology.menu;

public enum SystemMenu {

    MAIN_MENU,
    NEW_GOODS_MENU,
    KEYWORDS_MENU,
    EXIT_MENU,
    SHOWCASE_MENU,
    PAYMENT_MENU,
    SELECT_GOODS_MENU,
    QUANTITY_ORDER_GOODS_MENU,
    SORTING_MENU,
    ORDER_SEARCH_MENU,
    RATING_MENU,
    ADVICE_MENU,
    ORDER_MENU,
    DELIVERY_MENU,
    ORDER_REPEAT_MENU,
    GOODS_RETURN_MENU
}
